BUG: Remove fetching unused HBN dataset
Remove fetching unused HBN dataset.

Additionally, this fixes:
```
    deriv_path = op.join(study_path, "derivatives")
NameError: name 'op' is not defined
```